### ISSUE TITLE
Error while installing other npm packages

### ISSUE THREAD

**Issue by samuelbeard** [andithemudkip/p5-node#1]
When node-p5 is installed on a project, this error occurs whenever I try to install a new package.

```
npm ERR! path /Users/.../node_modules/node-p5
npm ERR! code EISGIT
npm ERR! git /Users/.../node_modules/node-p5: Appears to be a git repo or submodule.
npm ERR! git     /Users/.../node_modules/node-p5
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

I can get around this by deleting the node_modules directory, installing the new package I want then doing `npm install`.

**Comment by andithemudkip** [comment]
seems like npm was including the .git folder when publishing (which it shouldn't but oh well)
sorry it took like a month to notice this, I don't really check on this module often
it should be fine now if you update it to 1.0.2

**Comment by samuelbeard** [comment]
That's great thanks!
