### ISSUE TITLE
Axios dependency needs to be updated to allow for a higher version

### ISSUE THREAD

**Issue by dannyking** [andithemudkip/p5-node#8]
# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/axios
  node-p5  *
  Depends on vulnerable versions of axios
  node_modules/node-p5

**Comment by dannyking** [comment]
Sorry, I see that this has actually been addressed here in a pull request on March 31st, but I don't believe npm has been updated?

**Comment by andithemudkip** [comment]
yep, I just published the update on npm, should be alright once updated now
